# Generated by Django 5.0.4 on 2024-05-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoloyee', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=500)),
            ],
        ),
    ]
